export const Routes = {
	MEDICAL_RECORDS: '/medical-records',
	USER_PROFILE: '/user-profile',
	HOME: '/home',
	LOGIN: '/login',
	VACCINATION_RECORDS: '/vaccination-records',
	FOLLOW_UP: '/follow-up',
	ITEMS_LIST: '/items/list',
	ADD_ITEM: '/items/add',
	EDIT_ITEM: '/items/edit',
	BILLING_LIST: '/billing/list',
	ADD_BILLING_ITEM: '/billing/add',
	EDIT_BILLING_ITEM: '/billing/edit',
	BILLING_DETAILS: '/billing/details',
};
